language: csharp
mono: none

matrix:
  include:
    - dotnet: 2.2
      env:
        - SOLUTION="MinorEngine/MinorEngine.sln"
        - BUILDCONFIG="Release"


install:
  - dotnet restore ADL/
  - dotnet restore MinorEngine/
  - dotnet restore ext-pp/
  - dotnet restore opencl-dotnet/

script:
  - dotnet build ADL/ADL/ADL.sln -c $BUILDCONFIG
  - dotnet build $SOLUTION -c $BUILDCONFIG
  - dotnet build ext-pp/ext_pp.sln -c $BUILDCONFIG
  - dotnet build opencl-dotnet/OpenCl.DotNetCore.sln -c $BUILDCONFIG

after_script:
  - dotnet test $SOLUTION --collect:"XPlat Code Coverage"
  - bash <(curl -s https://codecov.io/bash)