language: csharp
mono: none
sudo: required

matrix:
  include:
    - dotnet: 2.2
      env:
        - SOLUTION="MinorEngine/MinorEngine.sln"
        - BUILDCONFIG="Release"

#Restore the Submodules and the Project
install:
    #Install GDI+
  - sudo apt-get install libgdiplus
  #Restore Projects
  - dotnet restore ADL/ADL/
  - dotnet restore ext-pp/
  - dotnet restore opencl-dotnet/
  - dotnet restore bepuphysics2/Library.sln
  - dotnet restore MinorEngine/ #<-- The Project


#Build the projects
#ADL has to be splitted into its subprojects since 2 of them are .Net Framework based and will not compile with .net Core
#Also the build order matters since the MinorEngine solution needs references from the other submodules
script:
  - dotnet build ADL/ADL/ADL/ADL.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Crash/ADL.Crash.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Network.Client/ADL.Network.Client.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Network.Server/ADL.Network.Server.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Network.Shared/ADL.Network.Shared.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.UnitTests/ADL.UnitTests.csproj -c $BUILDCONFIG
  - dotnet build ext-pp/ext_pp.sln -c $BUILDCONFIG
  - dotnet build opencl-dotnet/OpenCl.DotNetCore.sln -c $BUILDCONFIG
  - dotnet build bepuphysics2/Library.sln -c $BUILDCONFIG
  - dotnet build $SOLUTION -c $BUILDCONFIG

#Testing all included projects.
after_script:
  - dotnet test ext-pp/ext_pp.sln -p:Configuration=Release
  - dotnet test ADL/ADL/ADL.UnitTests/ADL.UnitTests.csproj -p:Configuration=Release
  - dotnet test $SOLUTION --collect:"XPlat Code Coverage" -p:Configuration=Release -p:DefineConstants=TRAVIS_TEST
  - bash <(curl -s https://codecov.io/bash) #Uploading the coverage report to Codecov.
