language: csharp
mono: none
sudo: required

matrix:
  include:
    - dotnet: 2.2
      env:
        - SOLUTION="MinorEngine/MinorEngine.sln"
        - BUILDCONFIG="Release"

before_install:
  - chmod -v 777 ./.travis/setup.sh
  - ./.travis/setup.sh

install:
  - dotnet restore ADL/ADL/
  - dotnet restore MinorEngine/
  - dotnet restore ext-pp/
  - dotnet restore opencl-dotnet/

script:
  - dotnet build ADL/ADL/ADL/ADL.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Crash/ADL.Crash.csproj -c $BUILDCONFIG
  - dotnet build ext-pp/ext_pp.sln -c $BUILDCONFIG
  - dotnet build opencl-dotnet/OpenCl.DotNetCore.sln -c $BUILDCONFIG
  - dotnet build $SOLUTION -c $BUILDCONFIG

after_script:
  - dotnet test $SOLUTION --collect:"XPlat Code Coverage" -p:Configuration=Release
  - bash <(curl -s https://codecov.io/bash)