language: csharp
mono: none
sudo: required
dist: xenial
services:
  - xvfb
addons:
    apt:
        packages:
        - fakeroot
        - libgdiplus
        - libalut0

matrix:
  include:
    - dotnet: 2.2
      env:
        - SOLUTION="Engine/Engine.sln"
        - BUILDCONFIG="Release"

#Restore the Submodules and the Project
install:
  - sudo chmod +x setupcl.sh
  - sudo bash setupcl.sh


  #Restore Projects
  - dotnet restore ADL/ADL/
  - dotnet restore ext-pp/
  - dotnet restore Engine/ #<-- The Project

#Build the projects
#ADL has to be splitted into its subprojects since 2 of them are .Net Framework based and will not compile with .net Core
#Also the build order matters since the MinorEngine solution needs references from the other submodules
script:
  - dotnet build ADL/ADL/ADL/ADL.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Crash/ADL.Crash.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Network.Client/ADL.Network.Client.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.Network.Shared/ADL.Network.Shared.csproj -c $BUILDCONFIG
  - dotnet build ADL/ADL/ADL.UnitTests/ADL.UnitTests.csproj -c $BUILDCONFIG
  - dotnet build ext-pp/ext_pp.sln -c $BUILDCONFIG
  - dotnet build $SOLUTION -c $BUILDCONFIG

#Testing all included projects.
after_script:
  - dotnet test $SOLUTION --collect:"XPlat Code Coverage" -c $BUILDCONFIG
  - bash <(curl -s https://codecov.io/bash) #Uploading the coverage report to Codecov.
